// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: japanapi/v1/japanapi_v1.proto

package japanapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoverageService_GetCoverage_FullMethodName = "/japanapi.v1.CoverageService/GetCoverage"
)

// CoverageServiceClient is the client API for CoverageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoverageServiceClient interface {
	GetCoverage(ctx context.Context, in *GetCoverageRequest, opts ...grpc.CallOption) (*GetCoverageResponse, error)
}

type coverageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoverageServiceClient(cc grpc.ClientConnInterface) CoverageServiceClient {
	return &coverageServiceClient{cc}
}

func (c *coverageServiceClient) GetCoverage(ctx context.Context, in *GetCoverageRequest, opts ...grpc.CallOption) (*GetCoverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoverageResponse)
	err := c.cc.Invoke(ctx, CoverageService_GetCoverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoverageServiceServer is the server API for CoverageService service.
// All implementations must embed UnimplementedCoverageServiceServer
// for forward compatibility.
type CoverageServiceServer interface {
	GetCoverage(context.Context, *GetCoverageRequest) (*GetCoverageResponse, error)
	mustEmbedUnimplementedCoverageServiceServer()
}

// UnimplementedCoverageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoverageServiceServer struct{}

func (UnimplementedCoverageServiceServer) GetCoverage(context.Context, *GetCoverageRequest) (*GetCoverageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoverage not implemented")
}
func (UnimplementedCoverageServiceServer) mustEmbedUnimplementedCoverageServiceServer() {}
func (UnimplementedCoverageServiceServer) testEmbeddedByValue()                         {}

// UnsafeCoverageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoverageServiceServer will
// result in compilation errors.
type UnsafeCoverageServiceServer interface {
	mustEmbedUnimplementedCoverageServiceServer()
}

func RegisterCoverageServiceServer(s grpc.ServiceRegistrar, srv CoverageServiceServer) {
	// If the following call panics, it indicates UnimplementedCoverageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoverageService_ServiceDesc, srv)
}

func _CoverageService_GetCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoverageServiceServer).GetCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoverageService_GetCoverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoverageServiceServer).GetCoverage(ctx, req.(*GetCoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoverageService_ServiceDesc is the grpc.ServiceDesc for CoverageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoverageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.CoverageService",
	HandlerType: (*CoverageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoverage",
			Handler:    _CoverageService_GetCoverage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}

const (
	DimensionService_ListMarkets_FullMethodName = "/japanapi.v1.DimensionService/ListMarkets"
	DimensionService_ListItems_FullMethodName   = "/japanapi.v1.DimensionService/ListItems"
	DimensionService_ListOrigins_FullMethodName = "/japanapi.v1.DimensionService/ListOrigins"
)

// DimensionServiceClient is the client API for DimensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DimensionServiceClient interface {
	ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	ListOrigins(ctx context.Context, in *ListOriginsRequest, opts ...grpc.CallOption) (*ListOriginsResponse, error)
}

type dimensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDimensionServiceClient(cc grpc.ClientConnInterface) DimensionServiceClient {
	return &dimensionServiceClient{cc}
}

func (c *dimensionServiceClient) ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMarketsResponse)
	err := c.cc.Invoke(ctx, DimensionService_ListMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dimensionServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, DimensionService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dimensionServiceClient) ListOrigins(ctx context.Context, in *ListOriginsRequest, opts ...grpc.CallOption) (*ListOriginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOriginsResponse)
	err := c.cc.Invoke(ctx, DimensionService_ListOrigins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DimensionServiceServer is the server API for DimensionService service.
// All implementations must embed UnimplementedDimensionServiceServer
// for forward compatibility.
type DimensionServiceServer interface {
	ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error)
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	ListOrigins(context.Context, *ListOriginsRequest) (*ListOriginsResponse, error)
	mustEmbedUnimplementedDimensionServiceServer()
}

// UnimplementedDimensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDimensionServiceServer struct{}

func (UnimplementedDimensionServiceServer) ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMarkets not implemented")
}
func (UnimplementedDimensionServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedDimensionServiceServer) ListOrigins(context.Context, *ListOriginsRequest) (*ListOriginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrigins not implemented")
}
func (UnimplementedDimensionServiceServer) mustEmbedUnimplementedDimensionServiceServer() {}
func (UnimplementedDimensionServiceServer) testEmbeddedByValue()                          {}

// UnsafeDimensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DimensionServiceServer will
// result in compilation errors.
type UnsafeDimensionServiceServer interface {
	mustEmbedUnimplementedDimensionServiceServer()
}

func RegisterDimensionServiceServer(s grpc.ServiceRegistrar, srv DimensionServiceServer) {
	// If the following call panics, it indicates UnimplementedDimensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DimensionService_ServiceDesc, srv)
}

func _DimensionService_ListMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DimensionServiceServer).ListMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DimensionService_ListMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DimensionServiceServer).ListMarkets(ctx, req.(*ListMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DimensionService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DimensionServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DimensionService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DimensionServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DimensionService_ListOrigins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOriginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DimensionServiceServer).ListOrigins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DimensionService_ListOrigins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DimensionServiceServer).ListOrigins(ctx, req.(*ListOriginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DimensionService_ServiceDesc is the grpc.ServiceDesc for DimensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DimensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.DimensionService",
	HandlerType: (*DimensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMarkets",
			Handler:    _DimensionService_ListMarkets_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _DimensionService_ListItems_Handler,
		},
		{
			MethodName: "ListOrigins",
			Handler:    _DimensionService_ListOrigins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}

const (
	PriceService_GetDailyPrices_FullMethodName  = "/japanapi.v1.PriceService/GetDailyPrices"
	PriceService_GetLatestPrices_FullMethodName = "/japanapi.v1.PriceService/GetLatestPrices"
	PriceService_GetPriceTrend_FullMethodName   = "/japanapi.v1.PriceService/GetPriceTrend"
	PriceService_GetPriceSummary_FullMethodName = "/japanapi.v1.PriceService/GetPriceSummary"
)

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceServiceClient interface {
	GetDailyPrices(ctx context.Context, in *GetDailyPricesRequest, opts ...grpc.CallOption) (*GetDailyPricesResponse, error)
	GetLatestPrices(ctx context.Context, in *GetLatestPricesRequest, opts ...grpc.CallOption) (*GetLatestPricesResponse, error)
	GetPriceTrend(ctx context.Context, in *GetPriceTrendRequest, opts ...grpc.CallOption) (*GetPriceTrendResponse, error)
	GetPriceSummary(ctx context.Context, in *GetPriceSummaryRequest, opts ...grpc.CallOption) (*GetPriceSummaryResponse, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) GetDailyPrices(ctx context.Context, in *GetDailyPricesRequest, opts ...grpc.CallOption) (*GetDailyPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyPricesResponse)
	err := c.cc.Invoke(ctx, PriceService_GetDailyPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetLatestPrices(ctx context.Context, in *GetLatestPricesRequest, opts ...grpc.CallOption) (*GetLatestPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestPricesResponse)
	err := c.cc.Invoke(ctx, PriceService_GetLatestPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetPriceTrend(ctx context.Context, in *GetPriceTrendRequest, opts ...grpc.CallOption) (*GetPriceTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceTrendResponse)
	err := c.cc.Invoke(ctx, PriceService_GetPriceTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) GetPriceSummary(ctx context.Context, in *GetPriceSummaryRequest, opts ...grpc.CallOption) (*GetPriceSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPriceSummaryResponse)
	err := c.cc.Invoke(ctx, PriceService_GetPriceSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility.
type PriceServiceServer interface {
	GetDailyPrices(context.Context, *GetDailyPricesRequest) (*GetDailyPricesResponse, error)
	GetLatestPrices(context.Context, *GetLatestPricesRequest) (*GetLatestPricesResponse, error)
	GetPriceTrend(context.Context, *GetPriceTrendRequest) (*GetPriceTrendResponse, error)
	GetPriceSummary(context.Context, *GetPriceSummaryRequest) (*GetPriceSummaryResponse, error)
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceServiceServer struct{}

func (UnimplementedPriceServiceServer) GetDailyPrices(context.Context, *GetDailyPricesRequest) (*GetDailyPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyPrices not implemented")
}
func (UnimplementedPriceServiceServer) GetLatestPrices(context.Context, *GetLatestPricesRequest) (*GetLatestPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestPrices not implemented")
}
func (UnimplementedPriceServiceServer) GetPriceTrend(context.Context, *GetPriceTrendRequest) (*GetPriceTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceTrend not implemented")
}
func (UnimplementedPriceServiceServer) GetPriceSummary(context.Context, *GetPriceSummaryRequest) (*GetPriceSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceSummary not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}
func (UnimplementedPriceServiceServer) testEmbeddedByValue()                      {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	// If the following call panics, it indicates UnimplementedPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_GetDailyPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetDailyPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_GetDailyPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetDailyPrices(ctx, req.(*GetDailyPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetLatestPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetLatestPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_GetLatestPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetLatestPrices(ctx, req.(*GetLatestPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetPriceTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetPriceTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_GetPriceTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetPriceTrend(ctx, req.(*GetPriceTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_GetPriceSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetPriceSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_GetPriceSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetPriceSummary(ctx, req.(*GetPriceSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyPrices",
			Handler:    _PriceService_GetDailyPrices_Handler,
		},
		{
			MethodName: "GetLatestPrices",
			Handler:    _PriceService_GetLatestPrices_Handler,
		},
		{
			MethodName: "GetPriceTrend",
			Handler:    _PriceService_GetPriceTrend_Handler,
		},
		{
			MethodName: "GetPriceSummary",
			Handler:    _PriceService_GetPriceSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}

const (
	AnalysisService_CompareMarkets_FullMethodName = "/japanapi.v1.AnalysisService/CompareMarkets"
	AnalysisService_RankItems_FullMethodName      = "/japanapi.v1.AnalysisService/RankItems"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	CompareMarkets(ctx context.Context, in *CompareMarketsRequest, opts ...grpc.CallOption) (*CompareMarketsResponse, error)
	RankItems(ctx context.Context, in *RankItemsRequest, opts ...grpc.CallOption) (*RankItemsResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) CompareMarkets(ctx context.Context, in *CompareMarketsRequest, opts ...grpc.CallOption) (*CompareMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareMarketsResponse)
	err := c.cc.Invoke(ctx, AnalysisService_CompareMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) RankItems(ctx context.Context, in *RankItemsRequest, opts ...grpc.CallOption) (*RankItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankItemsResponse)
	err := c.cc.Invoke(ctx, AnalysisService_RankItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
type AnalysisServiceServer interface {
	CompareMarkets(context.Context, *CompareMarketsRequest) (*CompareMarketsResponse, error)
	RankItems(context.Context, *RankItemsRequest) (*RankItemsResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) CompareMarkets(context.Context, *CompareMarketsRequest) (*CompareMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareMarkets not implemented")
}
func (UnimplementedAnalysisServiceServer) RankItems(context.Context, *RankItemsRequest) (*RankItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RankItems not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_CompareMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).CompareMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_CompareMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).CompareMarkets(ctx, req.(*CompareMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_RankItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).RankItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_RankItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).RankItems(ctx, req.(*RankItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompareMarkets",
			Handler:    _AnalysisService_CompareMarkets_Handler,
		},
		{
			MethodName: "RankItems",
			Handler:    _AnalysisService_RankItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}

const (
	IngestionService_ListIngestionRuns_FullMethodName  = "/japanapi.v1.IngestionService/ListIngestionRuns"
	IngestionService_ListIngestionFiles_FullMethodName = "/japanapi.v1.IngestionService/ListIngestionFiles"
)

// IngestionServiceClient is the client API for IngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestionServiceClient interface {
	ListIngestionRuns(ctx context.Context, in *ListIngestionRunsRequest, opts ...grpc.CallOption) (*ListIngestionRunsResponse, error)
	ListIngestionFiles(ctx context.Context, in *ListIngestionFilesRequest, opts ...grpc.CallOption) (*ListIngestionFilesResponse, error)
}

type ingestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionServiceClient(cc grpc.ClientConnInterface) IngestionServiceClient {
	return &ingestionServiceClient{cc}
}

func (c *ingestionServiceClient) ListIngestionRuns(ctx context.Context, in *ListIngestionRunsRequest, opts ...grpc.CallOption) (*ListIngestionRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIngestionRunsResponse)
	err := c.cc.Invoke(ctx, IngestionService_ListIngestionRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionServiceClient) ListIngestionFiles(ctx context.Context, in *ListIngestionFilesRequest, opts ...grpc.CallOption) (*ListIngestionFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIngestionFilesResponse)
	err := c.cc.Invoke(ctx, IngestionService_ListIngestionFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestionServiceServer is the server API for IngestionService service.
// All implementations must embed UnimplementedIngestionServiceServer
// for forward compatibility.
type IngestionServiceServer interface {
	ListIngestionRuns(context.Context, *ListIngestionRunsRequest) (*ListIngestionRunsResponse, error)
	ListIngestionFiles(context.Context, *ListIngestionFilesRequest) (*ListIngestionFilesResponse, error)
	mustEmbedUnimplementedIngestionServiceServer()
}

// UnimplementedIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionServiceServer struct{}

func (UnimplementedIngestionServiceServer) ListIngestionRuns(context.Context, *ListIngestionRunsRequest) (*ListIngestionRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIngestionRuns not implemented")
}
func (UnimplementedIngestionServiceServer) ListIngestionFiles(context.Context, *ListIngestionFilesRequest) (*ListIngestionFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIngestionFiles not implemented")
}
func (UnimplementedIngestionServiceServer) mustEmbedUnimplementedIngestionServiceServer() {}
func (UnimplementedIngestionServiceServer) testEmbeddedByValue()                          {}

// UnsafeIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionServiceServer will
// result in compilation errors.
type UnsafeIngestionServiceServer interface {
	mustEmbedUnimplementedIngestionServiceServer()
}

func RegisterIngestionServiceServer(s grpc.ServiceRegistrar, srv IngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionService_ServiceDesc, srv)
}

func _IngestionService_ListIngestionRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIngestionRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).ListIngestionRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionService_ListIngestionRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).ListIngestionRuns(ctx, req.(*ListIngestionRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionService_ListIngestionFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIngestionFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionServiceServer).ListIngestionFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionService_ListIngestionFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionServiceServer).ListIngestionFiles(ctx, req.(*ListIngestionFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestionService_ServiceDesc is the grpc.ServiceDesc for IngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.IngestionService",
	HandlerType: (*IngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIngestionRuns",
			Handler:    _IngestionService_ListIngestionRuns_Handler,
		},
		{
			MethodName: "ListIngestionFiles",
			Handler:    _IngestionService_ListIngestionFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}

const (
	SystemService_GetHealth_FullMethodName = "/japanapi.v1.SystemService/GetHealth"
	SystemService_GetReady_FullMethodName  = "/japanapi.v1.SystemService/GetReady"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	GetReady(ctx context.Context, in *GetReadyRequest, opts ...grpc.CallOption) (*GetReadyResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, SystemService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetReady(ctx context.Context, in *GetReadyRequest, opts ...grpc.CallOption) (*GetReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadyResponse)
	err := c.cc.Invoke(ctx, SystemService_GetReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	GetReady(context.Context, *GetReadyRequest) (*GetReadyResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedSystemServiceServer) GetReady(context.Context, *GetReadyRequest) (*GetReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReady not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}
func (UnimplementedSystemServiceServer) testEmbeddedByValue()                       {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetReady(ctx, req.(*GetReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "japanapi.v1.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _SystemService_GetHealth_Handler,
		},
		{
			MethodName: "GetReady",
			Handler:    _SystemService_GetReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "japanapi/v1/japanapi_v1.proto",
}
